# Generated by Django 4.2 on 2023-04-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('ur1', models.CharField(max_length=250, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
            ],
        ),
    ]
