# Generated by Django 4.2 on 2023-04-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='ur1',
            new_name='url',
        ),
    ]
