# Generated by Django 4.2 on 2023-04-25 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_team_created_date_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_member',
        ),
        migrations.AddField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(through='main.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
