# Generated by Django 4.2 on 2023-04-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_team_team_member_team_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_members',
        ),
    ]
