# Generated by Django 4.2 on 2023-04-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_team_memberships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='memberships',
        ),
    ]
