# Generated by Django 4.2 on 2023-05-02 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_log_delete_useraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='main.project'),
        ),
        migrations.AlterField(
            model_name='log',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='main.task'),
        ),
    ]
