# Generated by Django 4.2 on 2023-05-03 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_log_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
    ]
